# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1418, 851)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/RUDYicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QMainWindow#MainWindow{\n"
"    \n"
"    background-color:rgb(200, 200, 200);\n"
"    font: 10pt \"Microsoft Tai Le\";\n"
"}\n"
"QGroupBox{\n"
"    font: 75 12pt \"Microsoft Tai Le\";\n"
"}\n"
"QFrame#groupFrame,QFrame#groupFrame_2 {\n"
"    \n"
"    background-color:rgb(248, 233, 210);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}\n"
"QToolButton{\n"
"    \n"
"    background-color: rgb(204, 204, 204);\n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"}\n"
"QToolButton#prevPage{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}\n"
"QToolButton#nextPage{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}\n"
"QIcon{background-color:rga(1,1,1);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listGroup.sizePolicy().hasHeightForWidth())
        self.listGroup.setSizePolicy(sizePolicy)
        self.listGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.listGroup.setFlat(True)
        self.listGroup.setObjectName("listGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.listGroup)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupFrame = QtWidgets.QFrame(self.listGroup)
        self.groupFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.groupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupFrame.setLineWidth(1)
        self.groupFrame.setObjectName("groupFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupFrame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupFrame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.searchContacts = QtWidgets.QLineEdit(self.groupFrame)
        self.searchContacts.setObjectName("searchContacts")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.searchContacts)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.search = QtWidgets.QPushButton(self.groupFrame)
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.reset = QtWidgets.QPushButton(self.groupFrame)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.searchFirst = QtWidgets.QLineEdit(self.groupFrame)
        self.searchFirst.setObjectName("searchFirst")
        self.horizontalLayout_7.addWidget(self.searchFirst)
        self.searchLast = QtWidgets.QLineEdit(self.groupFrame)
        self.searchLast.setObjectName("searchLast")
        self.horizontalLayout_7.addWidget(self.searchLast)
        self.seeDeleted = QtWidgets.QCheckBox(self.groupFrame)
        self.seeDeleted.setObjectName("seeDeleted")
        self.horizontalLayout_7.addWidget(self.seeDeleted)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.searchAddr = QtWidgets.QLineEdit(self.groupFrame)
        self.searchAddr.setObjectName("searchAddr")
        self.gridLayout_10.addWidget(self.searchAddr, 0, 0, 1, 1)
        self.searchState = QtWidgets.QLineEdit(self.groupFrame)
        self.searchState.setMaximumSize(QtCore.QSize(75, 16777215))
        self.searchState.setObjectName("searchState")
        self.gridLayout_10.addWidget(self.searchState, 0, 2, 1, 1)
        self.searchCity = QtWidgets.QLineEdit(self.groupFrame)
        self.searchCity.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.searchCity.setObjectName("searchCity")
        self.gridLayout_10.addWidget(self.searchCity, 0, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_10)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev_page = QtWidgets.QToolButton(self.groupFrame)
        self.prev_page.setMaximumSize(QtCore.QSize(15, 15))
        self.prev_page.setIconSize(QtCore.QSize(10, 10))
        self.prev_page.setArrowType(QtCore.Qt.LeftArrow)
        self.prev_page.setObjectName("prev_page")
        self.horizontalLayout_2.addWidget(self.prev_page)
        self.page_num = QtWidgets.QComboBox(self.groupFrame)
        self.page_num.setMaximumSize(QtCore.QSize(16777215, 15))
        self.page_num.setStyleSheet("font: italic 9pt \"Microsoft Tai Le\";")
        self.page_num.setObjectName("page_num")
        self.horizontalLayout_2.addWidget(self.page_num)
        self.next_page = QtWidgets.QToolButton(self.groupFrame)
        self.next_page.setMaximumSize(QtCore.QSize(15, 15))
        self.next_page.setIconSize(QtCore.QSize(10, 10))
        self.next_page.setArrowType(QtCore.Qt.RightArrow)
        self.next_page.setObjectName("next_page")
        self.horizontalLayout_2.addWidget(self.next_page)
        self.total_pages = QtWidgets.QLabel(self.groupFrame)
        self.total_pages.setMaximumSize(QtCore.QSize(100, 15))
        self.total_pages.setStyleSheet("font: italic 9pt \"Microsoft Tai Le\";")
        self.total_pages.setObjectName("total_pages")
        self.horizontalLayout_2.addWidget(self.total_pages)
        spacerItem1 = QtWidgets.QSpacerItem(326, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.clientList = QtWidgets.QTableWidget(self.groupFrame)
        self.clientList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.clientList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.clientList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.clientList.setObjectName("clientList")
        self.clientList.setColumnCount(6)
        self.clientList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientList.setHorizontalHeaderItem(5, item)
        self.clientList.horizontalHeader().setDefaultSectionSize(75)
        self.verticalLayout.addWidget(self.clientList)
        self.verticalLayout_2.addWidget(self.groupFrame)
        self.horizontalLayout_6.addWidget(self.listGroup)
        self.detailGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailGroup.sizePolicy().hasHeightForWidth())
        self.detailGroup.setSizePolicy(sizePolicy)
        self.detailGroup.setStyleSheet("")
        self.detailGroup.setFlat(True)
        self.detailGroup.setObjectName("detailGroup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.detailGroup)
        self.verticalLayout_9.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupFrame_2 = QtWidgets.QFrame(self.detailGroup)
        self.groupFrame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.groupFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupFrame_2.setObjectName("groupFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupFrame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clientAddress = QtWidgets.QGroupBox(self.groupFrame_2)
        self.clientAddress.setFlat(True)
        self.clientAddress.setObjectName("clientAddress")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.clientAddress)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.clientAddress)
        self.frame_3.setStyleSheet("QFrame{ background-color: rgb(220, 220, 220); }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.addr1 = QtWidgets.QLineEdit(self.frame_3)
        self.addr1.setObjectName("addr1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.addr1)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.addr2 = QtWidgets.QLineEdit(self.frame_3)
        self.addr2.setObjectName("addr2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.addr2)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_9.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 0, 2, 1, 1)
        self.city = QtWidgets.QLineEdit(self.frame_3)
        self.city.setObjectName("city")
        self.gridLayout_9.addWidget(self.city, 1, 0, 1, 1)
        self.state = QtWidgets.QComboBox(self.frame_3)
        self.state.setObjectName("state")
        self.gridLayout_9.addWidget(self.state, 1, 1, 1, 1)
        self.zipcode = QtWidgets.QLineEdit(self.frame_3)
        self.zipcode.setMaximumSize(QtCore.QSize(75, 16777215))
        self.zipcode.setObjectName("zipcode")
        self.gridLayout_9.addWidget(self.zipcode, 1, 2, 1, 1)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_9)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.gridLayout_2.addWidget(self.clientAddress, 3, 0, 1, 1)
        self.clientInfo = QtWidgets.QGroupBox(self.groupFrame_2)
        self.clientInfo.setFlat(True)
        self.clientInfo.setObjectName("clientInfo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.clientInfo)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.clientInfo)
        self.frame.setStyleSheet("QFrame{ background-color: rgb(220, 220, 220); }")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.firstName = QtWidgets.QLineEdit(self.frame)
        self.firstName.setObjectName("firstName")
        self.gridLayout.addWidget(self.firstName, 1, 0, 1, 1)
        self.middleInitial = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleInitial.sizePolicy().hasHeightForWidth())
        self.middleInitial.setSizePolicy(sizePolicy)
        self.middleInitial.setMaximumSize(QtCore.QSize(75, 16777215))
        self.middleInitial.setObjectName("middleInitial")
        self.gridLayout.addWidget(self.middleInitial, 1, 1, 1, 1)
        self.lastName = QtWidgets.QLineEdit(self.frame)
        self.lastName.setObjectName("lastName")
        self.gridLayout.addWidget(self.lastName, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.frame)
        self.gridLayout_2.addWidget(self.clientInfo, 2, 0, 1, 1)
        self.clientContact = QtWidgets.QGroupBox(self.groupFrame_2)
        self.clientContact.setFlat(True)
        self.clientContact.setObjectName("clientContact")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.clientContact)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.clientContact)
        self.frame_4.setStyleSheet("QFrame{ background-color: rgb(220, 220, 220); }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.phone1 = QtWidgets.QLineEdit(self.frame_4)
        self.phone1.setObjectName("phone1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.phone1)
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.phone2 = QtWidgets.QLineEdit(self.frame_4)
        self.phone2.setObjectName("phone2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phone2)
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.email = QtWidgets.QLineEdit(self.frame_4)
        self.email.setObjectName("email")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.email)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.gridLayout_2.addWidget(self.clientContact, 3, 1, 1, 1)
        self.spouseInfo = QtWidgets.QGroupBox(self.groupFrame_2)
        self.spouseInfo.setFlat(True)
        self.spouseInfo.setCheckable(True)
        self.spouseInfo.setObjectName("spouseInfo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.spouseInfo)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.spouseInfo)
        self.frame_2.setStyleSheet("QFrame{ background-color: rgb(220, 220, 220); }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 2, 1, 1)
        self.firstName_2 = QtWidgets.QLineEdit(self.frame_2)
        self.firstName_2.setObjectName("firstName_2")
        self.gridLayout_5.addWidget(self.firstName_2, 1, 0, 1, 1)
        self.middleInitial_2 = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleInitial_2.sizePolicy().hasHeightForWidth())
        self.middleInitial_2.setSizePolicy(sizePolicy)
        self.middleInitial_2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.middleInitial_2.setObjectName("middleInitial_2")
        self.gridLayout_5.addWidget(self.middleInitial_2, 1, 1, 1, 1)
        self.lastName_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lastName_2.setObjectName("lastName_2")
        self.gridLayout_5.addWidget(self.lastName_2, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.gridLayout_2.addWidget(self.spouseInfo, 2, 1, 1, 1)
        self.clientAddress_3 = QtWidgets.QGroupBox(self.groupFrame_2)
        self.clientAddress_3.setFlat(True)
        self.clientAddress_3.setObjectName("clientAddress_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.clientAddress_3)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.notes = QtWidgets.QTextEdit(self.clientAddress_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes.sizePolicy().hasHeightForWidth())
        self.notes.setSizePolicy(sizePolicy)
        self.notes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.notes.setObjectName("notes")
        self.verticalLayout_7.addWidget(self.notes)
        self.gridLayout_2.addWidget(self.clientAddress_3, 2, 2, 2, 1)
        self.mattersGroup = QtWidgets.QGroupBox(self.groupFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mattersGroup.sizePolicy().hasHeightForWidth())
        self.mattersGroup.setSizePolicy(sizePolicy)
        self.mattersGroup.setObjectName("mattersGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.mattersGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addMatter = QtWidgets.QToolButton(self.mattersGroup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMatter.setIcon(icon1)
        self.addMatter.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.addMatter.setObjectName("addMatter")
        self.horizontalLayout_5.addWidget(self.addMatter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.includeDeteled = QtWidgets.QCheckBox(self.mattersGroup)
        self.includeDeteled.setObjectName("includeDeteled")
        self.horizontalLayout_5.addWidget(self.includeDeteled)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.matterList = QtWidgets.QTableWidget(self.mattersGroup)
        self.matterList.setObjectName("matterList")
        self.matterList.setColumnCount(6)
        self.matterList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.matterList.setHorizontalHeaderItem(5, item)
        self.matterList.horizontalHeader().setDefaultSectionSize(75)
        self.verticalLayout_8.addWidget(self.matterList)
        self.gridLayout_2.addWidget(self.mattersGroup, 4, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addClient = QtWidgets.QToolButton(self.groupFrame_2)
        self.addClient.setIcon(icon1)
        self.addClient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.addClient.setObjectName("addClient")
        self.horizontalLayout_3.addWidget(self.addClient)
        self.saveClientChanges = QtWidgets.QToolButton(self.groupFrame_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveClientChanges.setIcon(icon2)
        self.saveClientChanges.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.saveClientChanges.setObjectName("saveClientChanges")
        self.horizontalLayout_3.addWidget(self.saveClientChanges)
        self.editClient = QtWidgets.QToolButton(self.groupFrame_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/note.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editClient.setIcon(icon3)
        self.editClient.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.editClient.setObjectName("editClient")
        self.horizontalLayout_3.addWidget(self.editClient)
        self.clearContent = QtWidgets.QToolButton(self.groupFrame_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/clear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearContent.setIcon(icon4)
        self.clearContent.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clearContent.setObjectName("clearContent")
        self.horizontalLayout_3.addWidget(self.clearContent)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.deleteAccount = QtWidgets.QToolButton(self.groupFrame_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAccount.setIcon(icon5)
        self.deleteAccount.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.deleteAccount.setObjectName("deleteAccount")
        self.horizontalLayout_3.addWidget(self.deleteAccount)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupFrame_2)
        self.label_4.setStyleSheet("font: 75 12pt \"Microsoft Tai Le\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.clientNum = QtWidgets.QLineEdit(self.groupFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientNum.sizePolicy().hasHeightForWidth())
        self.clientNum.setSizePolicy(sizePolicy)
        self.clientNum.setObjectName("clientNum")
        self.horizontalLayout_4.addWidget(self.clientNum)
        self.donotrep = QtWidgets.QCheckBox(self.groupFrame_2)
        self.donotrep.setObjectName("donotrep")
        self.horizontalLayout_4.addWidget(self.donotrep)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 3)
        self.verticalLayout_9.addWidget(self.groupFrame_2)
        self.horizontalLayout_6.addWidget(self.detailGroup)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1418, 25))
        self.menubar.setObjectName("menubar")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionManage_Users = QtWidgets.QAction(MainWindow)
        self.actionManage_Users.setObjectName("actionManage_Users")
        self.actionManage_Matter_Types = QtWidgets.QAction(MainWindow)
        self.actionManage_Matter_Types.setObjectName("actionManage_Matter_Types")
        self.actionFile_Maintenance = QtWidgets.QAction(MainWindow)
        self.actionFile_Maintenance.setObjectName("actionFile_Maintenance")
        self.actionBuild_a_Report = QtWidgets.QAction(MainWindow)
        self.actionBuild_a_Report.setObjectName("actionBuild_a_Report")
        self.menuAdmin.addAction(self.actionManage_Matter_Types)
        self.menuAdmin.addAction(self.actionManage_Users)
        self.menuAdmin.addAction(self.actionFile_Maintenance)
        self.menuReports.addAction(self.actionBuild_a_Report)
        self.menubar.addAction(self.menuAdmin.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.searchContacts, self.search)
        MainWindow.setTabOrder(self.search, self.reset)
        MainWindow.setTabOrder(self.reset, self.clientList)
        MainWindow.setTabOrder(self.clientList, self.clientNum)
        MainWindow.setTabOrder(self.clientNum, self.donotrep)
        MainWindow.setTabOrder(self.donotrep, self.firstName)
        MainWindow.setTabOrder(self.firstName, self.middleInitial)
        MainWindow.setTabOrder(self.middleInitial, self.lastName)
        MainWindow.setTabOrder(self.lastName, self.spouseInfo)
        MainWindow.setTabOrder(self.spouseInfo, self.firstName_2)
        MainWindow.setTabOrder(self.firstName_2, self.middleInitial_2)
        MainWindow.setTabOrder(self.middleInitial_2, self.lastName_2)
        MainWindow.setTabOrder(self.lastName_2, self.addr1)
        MainWindow.setTabOrder(self.addr1, self.addr2)
        MainWindow.setTabOrder(self.addr2, self.city)
        MainWindow.setTabOrder(self.city, self.state)
        MainWindow.setTabOrder(self.state, self.zipcode)
        MainWindow.setTabOrder(self.zipcode, self.phone1)
        MainWindow.setTabOrder(self.phone1, self.phone2)
        MainWindow.setTabOrder(self.phone2, self.email)
        MainWindow.setTabOrder(self.email, self.notes)
        MainWindow.setTabOrder(self.notes, self.addMatter)
        MainWindow.setTabOrder(self.addMatter, self.matterList)
        MainWindow.setTabOrder(self.matterList, self.addClient)
        MainWindow.setTabOrder(self.addClient, self.saveClientChanges)
        MainWindow.setTabOrder(self.saveClientChanges, self.editClient)
        MainWindow.setTabOrder(self.editClient, self.clearContent)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rudy"))
        self.listGroup.setTitle(_translate("MainWindow", "Client List"))
        self.label.setText(_translate("MainWindow", "Search Name"))
        self.label_2.setText(_translate("MainWindow", "Search Address"))
        self.label_3.setText(_translate("MainWindow", "Search Phone or Email"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.searchFirst.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.searchLast.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.seeDeleted.setText(_translate("MainWindow", "Deleted"))
        self.searchAddr.setPlaceholderText(_translate("MainWindow", "Address"))
        self.searchState.setPlaceholderText(_translate("MainWindow", "State"))
        self.searchCity.setPlaceholderText(_translate("MainWindow", "City"))
        self.prev_page.setText(_translate("MainWindow", "..."))
        self.next_page.setText(_translate("MainWindow", "..."))
        self.total_pages.setText(_translate("MainWindow", "Of ## Pages"))
        item = self.clientList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client #"))
        item = self.clientList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.clientList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.clientList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "City"))
        item = self.clientList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "State"))
        item = self.clientList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Zip"))
        self.detailGroup.setTitle(_translate("MainWindow", "Client Details"))
        self.clientAddress.setTitle(_translate("MainWindow", "Address"))
        self.label_27.setText(_translate("MainWindow", "Address 1"))
        self.label_28.setText(_translate("MainWindow", "Address 2"))
        self.label_24.setText(_translate("MainWindow", "City"))
        self.label_25.setText(_translate("MainWindow", "State"))
        self.label_26.setText(_translate("MainWindow", "Zip"))
        self.clientInfo.setTitle(_translate("MainWindow", "Client Info"))
        self.label_5.setText(_translate("MainWindow", "First Name"))
        self.label_6.setText(_translate("MainWindow", "Middle Initial"))
        self.label_7.setText(_translate("MainWindow", "LastName"))
        self.clientContact.setTitle(_translate("MainWindow", "Contact"))
        self.label_33.setText(_translate("MainWindow", "Phone 1"))
        self.label_32.setText(_translate("MainWindow", "Phone 2"))
        self.label_34.setText(_translate("MainWindow", "Email"))
        self.spouseInfo.setTitle(_translate("MainWindow", "Married"))
        self.label_13.setText(_translate("MainWindow", "Spouse First Name"))
        self.label_14.setText(_translate("MainWindow", "Middle Initial"))
        self.label_15.setText(_translate("MainWindow", "Spouse LastName"))
        self.clientAddress_3.setTitle(_translate("MainWindow", "Notes"))
        self.mattersGroup.setTitle(_translate("MainWindow", "Client Matters"))
        self.addMatter.setText(_translate("MainWindow", "Add New Matter"))
        self.includeDeteled.setText(_translate("MainWindow", "Include Flagged for Deletion"))
        item = self.matterList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Matter #"))
        item = self.matterList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.matterList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Attorney"))
        item = self.matterList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date Opened"))
        item = self.matterList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Closed?"))
        item = self.matterList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "View Matter"))
        self.addClient.setText(_translate("MainWindow", "Add"))
        self.saveClientChanges.setText(_translate("MainWindow", "Save"))
        self.editClient.setText(_translate("MainWindow", "Edit"))
        self.clearContent.setText(_translate("MainWindow", "Clear"))
        self.deleteAccount.setText(_translate("MainWindow", "Delete"))
        self.label_4.setText(_translate("MainWindow", "Client #"))
        self.donotrep.setText(_translate("MainWindow", "Do Not Represent"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionManage_Users.setText(_translate("MainWindow", "Manage Users"))
        self.actionManage_Matter_Types.setText(_translate("MainWindow", "Manage Matter Types"))
        self.actionFile_Maintenance.setText(_translate("MainWindow", "File Maintenance"))
        self.actionBuild_a_Report.setText(_translate("MainWindow", "Build a Report"))


