# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MatterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatterWindow(object):
    def setupUi(self, MatterWindow):
        MatterWindow.setObjectName("MatterWindow")
        MatterWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MatterWindow.resize(1095, 610)
        MatterWindow.setStyleSheet("\n"
"QMainWindow#MainWindow{\n"
"    \n"
"    font: 10pt \"Microsoft Tai Le\";\n"
"    background-color:rgb(226, 226, 226);\n"
"}\n"
"QGroupBox{\n"
"    font: 75 12pt \"Microsoft Tai Le\";\n"
"}\n"
"QPushButton{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}\n"
"QToolButton{\n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"}\n"
"QToolButton#prevPage{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}\n"
"QToolButton#nextPage{\n"
"    \n"
"    font: 75 10pt \"Microsoft Tai Le\";\n"
"    color: rgb(202, 161, 56);\n"
"    background-color: rgb(11, 56, 97);\n"
"}")
        MatterWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MatterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("font: 75 12pt \"Microsoft Tai Le\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.clientNum = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientNum.sizePolicy().hasHeightForWidth())
        self.clientNum.setSizePolicy(sizePolicy)
        self.clientNum.setObjectName("clientNum")
        self.horizontalLayout_5.addWidget(self.clientNum)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setStyleSheet("font: 75 12pt \"Microsoft Tai Le\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.matterNum = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matterNum.sizePolicy().hasHeightForWidth())
        self.matterNum.setSizePolicy(sizePolicy)
        self.matterNum.setObjectName("matterNum")
        self.horizontalLayout_5.addWidget(self.matterNum)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.delete_matter = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_matter.setIcon(icon)
        self.delete_matter.setAutoRepeatDelay(300)
        self.delete_matter.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.delete_matter.setObjectName("delete_matter")
        self.horizontalLayout_5.addWidget(self.delete_matter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.matterGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.matterGroup.setFlat(True)
        self.matterGroup.setObjectName("matterGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.matterGroup)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.matterGroup)
        self.frame.setStyleSheet("QFrame{ background-color: rgb(248, 233, 210); }")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.attorneyInitials = QtWidgets.QLineEdit(self.frame)
        self.attorneyInitials.setObjectName("attorneyInitials")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.attorneyInitials)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.matterType = QtWidgets.QComboBox(self.frame)
        self.matterType.setObjectName("matterType")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.matterType)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateOpened = QtWidgets.QDateEdit(self.frame)
        self.dateOpened.setCalendarPopup(True)
        self.dateOpened.setProperty("showGroupSeparator", False)
        self.dateOpened.setObjectName("dateOpened")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateOpened)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.boxNumber = QtWidgets.QLineEdit(self.frame)
        self.boxNumber.setObjectName("boxNumber")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.boxNumber)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.closed = QtWidgets.QCheckBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closed.sizePolicy().hasHeightForWidth())
        self.closed.setSizePolicy(sizePolicy)
        self.closed.setObjectName("closed")
        self.horizontalLayout_4.addWidget(self.closed)
        self.dateClosed = QtWidgets.QDateEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateClosed.sizePolicy().hasHeightForWidth())
        self.dateClosed.setSizePolicy(sizePolicy)
        self.dateClosed.setCalendarPopup(True)
        self.dateClosed.setProperty("showGroupSeparator", False)
        self.dateClosed.setObjectName("dateClosed")
        self.horizontalLayout_4.addWidget(self.dateClosed)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.assets = QtWidgets.QDoubleSpinBox(self.frame)
        self.assets.setMaximum(9999999999.99)
        self.assets.setProperty("showGroupSeparator", True)
        self.assets.setObjectName("assets")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.assets)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.matterGroup)
        self.billingGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.billingGroup.setFlat(True)
        self.billingGroup.setObjectName("billingGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.billingGroup)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.billingGroup)
        self.frame_2.setStyleSheet("QFrame{ background-color: rgb(248, 233, 210); }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.firstName = QtWidgets.QLineEdit(self.frame_2)
        self.firstName.setObjectName("firstName")
        self.gridLayout.addWidget(self.firstName, 2, 0, 1, 1)
        self.lastName = QtWidgets.QLineEdit(self.frame_2)
        self.lastName.setObjectName("lastName")
        self.gridLayout.addWidget(self.lastName, 2, 2, 1, 1)
        self.middleInitial = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleInitial.sizePolicy().hasHeightForWidth())
        self.middleInitial.setSizePolicy(sizePolicy)
        self.middleInitial.setMaximumSize(QtCore.QSize(75, 16777215))
        self.middleInitial.setObjectName("middleInitial")
        self.gridLayout.addWidget(self.middleInitial, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.addr1 = QtWidgets.QLineEdit(self.frame_2)
        self.addr1.setObjectName("addr1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.addr1)
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.addr2 = QtWidgets.QLineEdit(self.frame_2)
        self.addr2.setObjectName("addr2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.addr2)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_2)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_2)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 0, 2, 1, 1)
        self.billCity = QtWidgets.QLineEdit(self.frame_2)
        self.billCity.setObjectName("billCity")
        self.gridLayout_10.addWidget(self.billCity, 1, 0, 1, 1)
        self.billState = QtWidgets.QComboBox(self.frame_2)
        self.billState.setObjectName("billState")
        self.gridLayout_10.addWidget(self.billState, 1, 1, 1, 1)
        self.billZip = QtWidgets.QLineEdit(self.frame_2)
        self.billZip.setMaximumSize(QtCore.QSize(75, 16777215))
        self.billZip.setObjectName("billZip")
        self.gridLayout_10.addWidget(self.billZip, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.useClientAddress = QtWidgets.QToolButton(self.billingGroup)
        self.useClientAddress.setObjectName("useClientAddress")
        self.gridLayout_2.addWidget(self.useClientAddress, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.billingGroup)
        self.frame_4.setStyleSheet("QFrame{ background-color: rgb(248, 233, 210); }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.phone1 = QtWidgets.QLineEdit(self.frame_4)
        self.phone1.setObjectName("phone1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.phone1)
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.phone2 = QtWidgets.QLineEdit(self.frame_4)
        self.phone2.setObjectName("phone2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phone2)
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.email = QtWidgets.QLineEdit(self.frame_4)
        self.email.setObjectName("email")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.email)
        self.gridLayout_2.addWidget(self.frame_4, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.billingGroup)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.documentGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.documentGroup.setFlat(True)
        self.documentGroup.setObjectName("documentGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.documentGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.setDirectory = QtWidgets.QToolButton(self.documentGroup)
        self.setDirectory.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.setDirectory.setObjectName("setDirectory")
        self.horizontalLayout_6.addWidget(self.setDirectory)
        self.clearPath = QtWidgets.QToolButton(self.documentGroup)
        self.clearPath.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clearPath.setObjectName("clearPath")
        self.horizontalLayout_6.addWidget(self.clearPath)
        self.currentDir = QtWidgets.QLineEdit(self.documentGroup)
        self.currentDir.setReadOnly(True)
        self.currentDir.setObjectName("currentDir")
        self.horizontalLayout_6.addWidget(self.currentDir)
        self.attachDocument = QtWidgets.QToolButton(self.documentGroup)
        self.attachDocument.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.attachDocument.setObjectName("attachDocument")
        self.horizontalLayout_6.addWidget(self.attachDocument)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.documentList = QtWidgets.QTableWidget(self.documentGroup)
        self.documentList.setObjectName("documentList")
        self.documentList.setColumnCount(4)
        self.documentList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.documentList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.documentList.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.documentList)
        self.horizontalLayout_7.addWidget(self.documentGroup)
        self.adversePartyGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.adversePartyGroup.setFlat(True)
        self.adversePartyGroup.setObjectName("adversePartyGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.adversePartyGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.adversePartyGroup)
        self.frame_3.setStyleSheet("QFrame{ background-color: rgb(248, 233, 210); }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.apFirst = QtWidgets.QLineEdit(self.frame_3)
        self.apFirst.setObjectName("apFirst")
        self.gridLayout_3.addWidget(self.apFirst, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 1)
        self.apMiddle = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apMiddle.sizePolicy().hasHeightForWidth())
        self.apMiddle.setSizePolicy(sizePolicy)
        self.apMiddle.setMaximumSize(QtCore.QSize(75, 16777215))
        self.apMiddle.setObjectName("apMiddle")
        self.gridLayout_3.addWidget(self.apMiddle, 2, 1, 1, 1)
        self.apLast = QtWidgets.QLineEdit(self.frame_3)
        self.apLast.setObjectName("apLast")
        self.gridLayout_3.addWidget(self.apLast, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.apNew = QtWidgets.QToolButton(self.frame_3)
        self.apNew.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.apNew.setObjectName("apNew")
        self.horizontalLayout_3.addWidget(self.apNew)
        self.apSave = QtWidgets.QToolButton(self.frame_3)
        self.apSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.apSave.setObjectName("apSave")
        self.horizontalLayout_3.addWidget(self.apSave)
        self.apClear = QtWidgets.QToolButton(self.frame_3)
        self.apClear.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.apClear.setObjectName("apClear")
        self.horizontalLayout_3.addWidget(self.apClear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.apDelete = QtWidgets.QToolButton(self.frame_3)
        self.apDelete.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.apDelete.setObjectName("apDelete")
        self.horizontalLayout_3.addWidget(self.apDelete)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.reason = QtWidgets.QLineEdit(self.frame_3)
        self.reason.setObjectName("reason")
        self.horizontalLayout_2.addWidget(self.reason)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.partyList = QtWidgets.QTableWidget(self.adversePartyGroup)
        self.partyList.setObjectName("partyList")
        self.partyList.setColumnCount(4)
        self.partyList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.partyList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.partyList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.partyList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.partyList.setHorizontalHeaderItem(3, item)
        self.verticalLayout_6.addWidget(self.partyList)
        self.horizontalLayout_7.addWidget(self.adversePartyGroup)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        MatterWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MatterWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MatterWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MatterWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionEdit = QtWidgets.QAction(MatterWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/note.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon2)
        self.actionEdit.setObjectName("actionEdit")
        self.actionClose = QtWidgets.QAction(MatterWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/arrow-1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon3)
        self.actionClose.setObjectName("actionClose")
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MatterWindow)
        QtCore.QMetaObject.connectSlotsByName(MatterWindow)
        MatterWindow.setTabOrder(self.clientNum, self.matterNum)
        MatterWindow.setTabOrder(self.matterNum, self.attorneyInitials)
        MatterWindow.setTabOrder(self.attorneyInitials, self.matterType)
        MatterWindow.setTabOrder(self.matterType, self.dateOpened)
        MatterWindow.setTabOrder(self.dateOpened, self.boxNumber)
        MatterWindow.setTabOrder(self.boxNumber, self.closed)
        MatterWindow.setTabOrder(self.closed, self.dateClosed)
        MatterWindow.setTabOrder(self.dateClosed, self.assets)
        MatterWindow.setTabOrder(self.assets, self.useClientAddress)
        MatterWindow.setTabOrder(self.useClientAddress, self.firstName)
        MatterWindow.setTabOrder(self.firstName, self.middleInitial)
        MatterWindow.setTabOrder(self.middleInitial, self.lastName)
        MatterWindow.setTabOrder(self.lastName, self.addr1)
        MatterWindow.setTabOrder(self.addr1, self.addr2)
        MatterWindow.setTabOrder(self.addr2, self.billCity)
        MatterWindow.setTabOrder(self.billCity, self.billState)
        MatterWindow.setTabOrder(self.billState, self.billZip)
        MatterWindow.setTabOrder(self.billZip, self.phone1)
        MatterWindow.setTabOrder(self.phone1, self.phone2)
        MatterWindow.setTabOrder(self.phone2, self.email)
        MatterWindow.setTabOrder(self.email, self.apFirst)
        MatterWindow.setTabOrder(self.apFirst, self.apMiddle)
        MatterWindow.setTabOrder(self.apMiddle, self.apLast)
        MatterWindow.setTabOrder(self.apLast, self.reason)
        MatterWindow.setTabOrder(self.reason, self.apNew)
        MatterWindow.setTabOrder(self.apNew, self.apSave)
        MatterWindow.setTabOrder(self.apSave, self.apClear)
        MatterWindow.setTabOrder(self.apClear, self.apDelete)
        MatterWindow.setTabOrder(self.apDelete, self.partyList)
        MatterWindow.setTabOrder(self.partyList, self.documentList)
        MatterWindow.setTabOrder(self.documentList, self.setDirectory)
        MatterWindow.setTabOrder(self.setDirectory, self.currentDir)
        MatterWindow.setTabOrder(self.currentDir, self.attachDocument)

    def retranslateUi(self, MatterWindow):
        _translate = QtCore.QCoreApplication.translate
        MatterWindow.setWindowTitle(_translate("MatterWindow", "Matter Details"))
        self.label_5.setText(_translate("MatterWindow", "Matter #"))
        self.label_11.setText(_translate("MatterWindow", "."))
        self.delete_matter.setText(_translate("MatterWindow", "Delete"))
        self.matterGroup.setTitle(_translate("MatterWindow", "Matter Info"))
        self.label.setText(_translate("MatterWindow", "Attorney Initials"))
        self.label_2.setText(_translate("MatterWindow", "Matter Type"))
        self.label_3.setText(_translate("MatterWindow", "Date Opened"))
        self.label_9.setText(_translate("MatterWindow", "Date Closed"))
        self.label_10.setText(_translate("MatterWindow", "Box Number"))
        self.closed.setText(_translate("MatterWindow", "Closed"))
        self.label_4.setText(_translate("MatterWindow", "Estate Assets"))
        self.assets.setSpecialValueText(_translate("MatterWindow", "No Assets"))
        self.assets.setPrefix(_translate("MatterWindow", "$ "))
        self.billingGroup.setTitle(_translate("MatterWindow", "Billing Info"))
        self.label_8.setText(_translate("MatterWindow", "LastName"))
        self.label_6.setText(_translate("MatterWindow", "First Name"))
        self.label_7.setText(_translate("MatterWindow", "Middle Initial"))
        self.label_27.setText(_translate("MatterWindow", "Address 1"))
        self.label_28.setText(_translate("MatterWindow", "Address 2"))
        self.label_29.setText(_translate("MatterWindow", "City"))
        self.label_30.setText(_translate("MatterWindow", "State"))
        self.label_31.setText(_translate("MatterWindow", "Zip"))
        self.useClientAddress.setText(_translate("MatterWindow", "Same as Client"))
        self.label_12.setText(_translate("MatterWindow", "Phone 1"))
        self.label_13.setText(_translate("MatterWindow", "Phone 2"))
        self.label_18.setText(_translate("MatterWindow", "Email"))
        self.documentGroup.setTitle(_translate("MatterWindow", "Original Documents"))
        self.setDirectory.setText(_translate("MatterWindow", "Set Directory"))
        self.clearPath.setText(_translate("MatterWindow", "Clear Dir."))
        self.attachDocument.setText(_translate("MatterWindow", "Add New Document(s)"))
        item = self.documentList.horizontalHeaderItem(0)
        item.setText(_translate("MatterWindow", "Delete"))
        item = self.documentList.horizontalHeaderItem(1)
        item.setText(_translate("MatterWindow", "Name"))
        item = self.documentList.horizontalHeaderItem(2)
        item.setText(_translate("MatterWindow", "FileDirectory"))
        item = self.documentList.horizontalHeaderItem(3)
        item.setText(_translate("MatterWindow", "View"))
        self.adversePartyGroup.setTitle(_translate("MatterWindow", "Adverse Parties"))
        self.label_14.setText(_translate("MatterWindow", "First Name"))
        self.label_16.setText(_translate("MatterWindow", "LastName"))
        self.label_15.setText(_translate("MatterWindow", "Middle Initial"))
        self.apNew.setText(_translate("MatterWindow", "New"))
        self.apSave.setText(_translate("MatterWindow", "Save"))
        self.apClear.setText(_translate("MatterWindow", "Clear"))
        self.apDelete.setText(_translate("MatterWindow", "Delete"))
        self.label_17.setText(_translate("MatterWindow", "Reason"))
        item = self.partyList.horizontalHeaderItem(0)
        item.setText(_translate("MatterWindow", "First Name"))
        item = self.partyList.horizontalHeaderItem(1)
        item.setText(_translate("MatterWindow", "M.I."))
        item = self.partyList.horizontalHeaderItem(2)
        item.setText(_translate("MatterWindow", "Last Name"))
        item = self.partyList.horizontalHeaderItem(3)
        item.setText(_translate("MatterWindow", "Reason"))
        self.toolBar.setWindowTitle(_translate("MatterWindow", "toolBar"))
        self.actionSave.setText(_translate("MatterWindow", "Save"))
        self.actionEdit.setText(_translate("MatterWindow", "Edit"))
        self.actionClose.setText(_translate("MatterWindow", "Close"))


